config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get    '/locationData', to: 'articles#locationData'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :abbr_date

  def abbr_date
    self.abbr_date = date_of_news.strftime("%b. %d").strip if date_of_news
  end

  def abbr_date_month
    self.abbr_date = date_of_news.strftime("%b.").strip if date_of_news
  end

  def abbr_date_day
    self.abbr_date = date_of_news.strftime("%e").strip if date_of_news
  end

  # To return abbr_date in as json
  def as_json options=nil
    options ||= {}
    options[:methods] = ((options[:methods] || []) + [:abbr_date, :abbr_date_month, :abbr_date_day])
    super options
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, except: [:locationData]
  require 'httparty'

  def index
    @articles = Article.all.order(id: :desc)
  end

  def new
    @article = Article.new
  end

  def show
    @article ||= Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)

    if @article.summary.blank?
      smmry_key = Rails.application.secrets.smmry_key

      smmry_url = "http://api.smmry.com/?SM_API_KEY=#{smmry_key}&SM_URL=#{@article.url}"
      response = HTTParty.get(smmry_url)
      response = response.parsed_response

      @article.summary = response["sm_api_content"] unless response["sm_api_content"].blank?
    end

    if @article.save
      redirect_to articles_path
    else
      render "new"
    end
  end

  def edit
    @article = Article.find params[:id]
  end

  def update
    @article = Article.find params[:id]
    if @article.update_attributes article_params
      redirect_to articles_path
    else
      render :action => :edit
    end
  end

  def destroy
    @article = Article.find params[:id]
    @article.destroy
    redirect_to articles_path
  end

  def locationData
    render json: Article.all.order(id: :desc).as_json(only: [:description, :location, :date_of_news, :summary, :url, :abbr_date])
  end

  private

  def article_params
    params.require(:article).permit(:description, :url, :video_embed, :location, :date_of_news, :summary)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to :controller => 'articles', :action => 'index' if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to :controller => 'articles', :action => 'index'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # return the articles container React component
    render component: 'ArticlesContainer'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url
    end
  end
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/views/articles/_form.slim
= form_for @article do |f|
  p
    = f.label :description
    = f.text_field :description, :required => true
  p
      = f.label :summary
      = f.text_field :summary
  p
    = f.label :url
    = f.text_field :url, :required => true
  p
    = f.label :video_embed
    = f.text_field :video_embed
  p
    = f.label :location
    = f.text_field :location
  p
    = f.label :date_of_news
    = f.text_field :date_of_news, :required => true, :class => 'date_of_news_picker'
  p
    = f.submit "Submit"

app/views/articles/edit.slim
.content
  fieldset
    = form_for :article, :url => article_path(@article), method: :put do |f|
      p
        = f.label :description
        = f.text_field :description, :required => true
      p
          = f.label :summary
          = f.text_field :summary
      p
        = f.label :url
        = f.text_field :url, :required => true
      p
        = f.label :video_embed
        = f.text_field :video_embed
      p
        = f.label :location
        = f.text_field :location
      p
        = f.label :date_of_news
        = f.text_field :date_of_news, :required => true, :class => 'date_of_news_picker'
      p
        = f.submit "Submit"
        = link_to("Remove", article_path(@article), method: :delete, class: "btn secondary")

app/views/articles/index.slim
.article-row
  h2  Articles
  .pull-right.nav-bar
    = link_to "New", new_article_path, class: "btn"
    = link_to "Logout", '/logout', class: "btn secondary"
  hr
.article-row
  table
    thead
      th Id
      th Date
      th Description
    tbody
    - @articles.each do |a|
      tr
        td
          a href="/articles/#{a.id}" #{a.id}
        td #{a.created_at}
        td #{a.description}

app/views/articles/new.slim
.content
  fieldset
    = render :partial => 'form'

app/views/articles/show.slim
.content
  .article-row
    fieldset
      ul
        li
          span.article_title Description:
          span
            b = @article.description
          hr
        li
          span.article_title Summary:
          span
            b = @article.summary
          hr
        li
          span.article_title URL:
          span
            b = @article.url
          hr
        li
          span.article_title Video Embed:
          span
            b = @article.video_embed
          hr
        li
          span.article_title Location:
          span
            b = @article.location
          hr
        li
          span.article_title Date of News:
          span
            b = @article.date_of_news
          hr

      = button_to 'Edit', edit_article_path(@article), :method => :get

app/views/layouts/_footer.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80893747-1', 'pokepain.com');
  ga('send', 'pageview');
</script>

app/views/layouts/application.slim
doctype html
html
  head
    title PokePain
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8rj5YgkFQe2mtsca8BbDqOdE4IYhkmjk"
    == yield :head
  body
    .main-container
      .center-content
        == yield
  = render 'layouts/footer'

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>